### ISSUE TITLE
Some packaged builds don't run on other machines

### ISSUE THREAD

**Issue by victorporof** [victorporof/tofino#46]
Me and @bwinton were investigating this today, and after getting packaging for macOS working on a Windows machine, trying to actually run the build on macOS failed with:

1. "The application “BFGBrowser” can’t be opened."
We fixed this by forcing `chmod a+x BFGBrowser.app/Contents/MacOS/BFGBrowser`

2. An uncaught exception which seems to originate from the fact that paths are borked with inconsistent separators. As for package contents, everything seems to be there
```
Uncaught Exception:
Error: Cannot find module '/Users/victorporof/Downloads/BFGBrowser.app/Contents/Resources/app/browser-runner\platform-electron\index.js'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/victorporof/Downloads/BFGBrowser.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (/Users/victorporof/Downloads/BFGBrowser.app/Contents/Resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/Users/victorporof/Downloads/BFGBrowser.app/Contents/Resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

That particular path originates from here: https://github.com/victorporof/tofino/blob/cbc9066f932c7dd62d45211d44fbbe136972d3b9/build/tasks/task-package.js#L29. While `electron` wants a `main` field in a package.json, it might be the case that it needs forward slashes regardless of platform.

**Comment by victorporof** [comment]
There have been reports of such errors regardless of whether or not builds were packaged on the same OS as the one on an end-users machine. I suspect it might be the first permissions problem described above.

**Comment by victorporof** [comment]
For all the tens of thousands of people trying to fix this bug, just letting you know that @bwinton had a fix for the path issue (1) described in the first comment.
